<?php

declare(strict_types=1);

namespace Bref\LaravelDsql\Test\Unit;

use Bref\LaravelDsql\DsqlConnection;
use Closure;
use Illuminate\Database\Schema\Blueprint;
use LogicException;
use PDO;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\TestWith;
use PHPUnit\Framework\TestCase;

final class DsqlSchemaGrammarTest extends TestCase
{
    public function test_declares_the_keys_and_constraints_of_a_new_table_in_its_creation(): void
    {
        $this->assertSame([
            'create table "games" ("id" uuid not null, "league_id" uuid not null, "team_id" uuid not null, "number" varchar(16) not null, "date" date not null, '
            . 'primary key ("id"), '
            . 'constraint "games_league_id_number_unique" unique ("league_id", "number"), '
            . 'constraint "games_league_id_foreign" foreign key ("league_id") references "leagues" ("id"), '
            . 'constraint "games_team_id_foreign" foreign key ("team_id") references "teams" ("id") on delete cascade on update cascade)',
            'create index async "games_date_index" on "games" ("date")',
        ], $this->sql(function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('league_id')->constrained();
            $table->foreignUuid('team_id')->constrained('teams')->cascadeOnDelete()->cascadeOnUpdate();
            $table->string('number', 16);
            $table->date('date')->index();

            $table->unique(['league_id', 'number']);
        }));
    }

    #[TestWith(['bigIncrements'])]
    #[TestWith(['increments'])]
    #[TestWith(['smallIncrements'])]
    public function test_turns_auto_incrementing_columns_into_identity_columns(string $type): void
    {
        $this->assertSame([
            'create table "games" ("id" bigint generated by default as identity (cache 1) not null primary key)',
        ], $this->sql(fn(Blueprint $table): mixed => $table->{$type}('id')));
    }

    public function test_keeps_integers_that_do_not_auto_increment(): void
    {
        $this->assertSame([
            'create table "games" ("expiration" bigint not null, "batch" integer not null, "points" smallint not null)',
        ], $this->sql(function (Blueprint $table): void {
            $table->bigInteger('expiration');
            $table->integer('batch');
            $table->smallInteger('points');
        }));
    }

    public function test_builds_the_indexes_and_foreign_keys_of_an_existing_table_in_the_background(): void
    {
        $this->assertSame([
            'create unique index async "games_number_unique" on "games" ("number")',
            'create index async "games_team_id_date_index" on "games" ("team_id", "date")',
            'alter table "games" add constraint "games_venue_id_foreign" foreign key ("venue_id") references "venues" ("id") on delete set null not valid',
        ], $this->sql(function (Blueprint $table): void {
            $table->unique('number');
            $table->index(['team_id', 'date']);
            $table->foreign('venue_id')->references('id')->on('venues')->nullOnDelete();
        }, creation: false));
    }

    public function test_refuses_a_primary_key_on_an_existing_table(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('Aurora DSQL only accepts a primary key when creating the table.');

        $this->sql(fn(Blueprint $table): mixed => $table->primary('id'), creation: false);
    }

    public function test_refuses_to_drop_a_primary_key(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('Aurora DSQL cannot drop the primary key of a table.');

        $this->sql(fn(Blueprint $table): mixed => $table->dropPrimary(), creation: false);
    }

    public function test_adds_nullable_columns_to_an_existing_table(): void
    {
        $this->assertSame([
            'alter table "games" add column "venue" varchar(255) null',
            'alter table "games" add column "played_at" timestamp(0) without time zone null',
            'create index async "games_venue_index" on "games" ("venue")',
        ], $this->sql(function (Blueprint $table): void {
            $table->string('venue')->nullable()->index();
            $table->timestamp('played_at')->nullable();
        }, creation: false));
    }

    public function test_refuses_to_add_a_column_that_is_not_nullable_to_an_existing_table(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('Aurora DSQL can only add nullable columns to an existing table: declare "venue" as nullable().');

        $this->sql(fn(Blueprint $table): mixed => $table->string('venue')->default('Home'), creation: false);
    }

    /**
     * @param  Closure(Blueprint): mixed  $column
     */
    #[DataProvider('columns_with_a_default_value')]
    public function test_refuses_to_add_a_column_with_a_default_value_to_an_existing_table(Closure $column): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('Aurora DSQL can only add columns without a default value to an existing table: add "pool" without a default, then set it with ->nullable()->default(…)->change(). The rows that already exist keep null.');

        $this->sql($column, creation: false);
    }

    /**
     * @return iterable<string, array{Closure(Blueprint): mixed}>
     */
    public static function columns_with_a_default_value(): iterable
    {
        yield 'default' => [fn(Blueprint $table): mixed => $table->string('pool')->nullable()->default('A')];

        yield 'current timestamp' => [fn(Blueprint $table): mixed => $table->timestamp('pool')->nullable()->useCurrent()];

        yield 'generated' => [fn(Blueprint $table): mixed => $table->integer('pool')->nullable()->storedAs('1 + 1')];
    }

    public function test_drops_unique_keys_declared_with_the_table_or_added_later(): void
    {
        $this->assertSame([
            'alter table "games" drop constraint if exists "games_number_unique"',
            'drop index if exists "games_number_unique"',
        ], $this->sql(fn(Blueprint $table): mixed => $table->dropUnique(['number']), creation: false));
    }

    public function test_makes_a_column_nullable_without_changing_its_type(): void
    {
        $this->assertSame([
            'alter table "games" alter column "venue" drop not null, alter column "venue" drop default, alter column "venue" drop identity if exists',
            'alter table "games" alter column "pool" drop not null, alter column "pool" set default \'A\', alter column "pool" drop identity if exists',
        ], $this->sql(function (Blueprint $table): void {
            $table->string('venue')->nullable()->change();
            $table->string('pool', 8)->nullable()->default('A')->change();
        }, creation: false));
    }

    public function test_keeps_the_comments_of_columns(): void
    {
        $this->assertSame([
            'alter table "games" alter column "venue" drop not null, alter column "venue" drop default, alter column "venue" drop identity if exists',
            'comment on column "games"."venue" is \'Where the game is played\'',
        ], $this->sql(function (Blueprint $table): void {
            $table->string('venue')->nullable()->comment('Where the game is played')->change();
        }, creation: false));
    }

    public function test_refuses_to_forbid_nulls_in_an_existing_column(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('Aurora DSQL can only change a column into a nullable column, of the same type.');

        $this->sql(fn(Blueprint $table): mixed => $table->string('venue')->change(), creation: false);
    }

    /**
     * @return list<string>
     */
    private function sql(Closure $callback, bool $creation = true): array
    {
        $connection = new DsqlConnection(fn(): PDO => throw new LogicException('No query expected.'));
        $connection->useDefaultSchemaGrammar();

        $blueprint = new Blueprint($connection, 'games');

        if ($creation) {
            $blueprint->create();
        }

        $callback($blueprint);

        return array_values($blueprint->toSql());
    }
}
